apiVersion: v1
kind: Service
metadata:
  name: odoo-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#kubectl expose deployment odoo-deployment --type=LoadBalancer --name=odoo-web-app