apiVersion: v1
kind: PersistentVolumeClaim #Create PVC
metadata:
  name: postgresql-data-claim #Create PVC
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size

